title: John's Site
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
collections:
  - articles
  - thoughts
  - projects
collections:
  articles:
    output: true
  thoughts:
    output: true
  projects:
    output: true
