title: John's Site
description: My site
theme:
  jekyll-theme-primer
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
collections:
  - articles
  - thoughts
collections:
  articles:
    output: true
  thoughts:
    output: true
