title: John's Site
remote_theme: rundocs/jekyll-rtd-theme
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
collections:
  - articles
  - thoughts
collections:
  articles:
    output: true
  thoughts:
    output: true
