title: John Goalby
description: My site
theme:
  jekyll-theme-primer
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
collections:
  - articles
collections:
  articles:
    output: true